"""Byte-identity GOLDEN tests for the MQL5 codegen engine.

These lock the EXACT generated MQL5 string for a representative set of graphs
(SMA / RSI / MACD operands, a Stochastic %K/%D graph, and crossing graphs that
exercise the ``[s]``/``[s+1]`` indices plus the ``s+2`` copy depth). They are the
acceptance gate for the indicator-multi-output FOUNDATION refactor: every change
in that effort is additive and DORMANT-by-default, so each golden below MUST stay
byte-identical before and after the refactor.

Do NOT edit a golden to "fix" a failing test — a diff here means the refactor
changed an existing graph's output, which violates the byte-identity invariant.
"""

from __future__ import annotations

from aether_api.services.codegen import generate_mql5


def _wrap(ea_name: str, body: str) -> str:
    """Return the full EA file for ``body`` lines inside ``OnTick``.

    The title-box trailing pad is a FIXED 24 spaces regardless of EA-name length
    (the current generator does not realign the border), captured verbatim from
    the generator output.
    """
    pad = " " * 24
    return (
        "//+------------------------------------------------------------------+\n"
        f"//| {ea_name}.mq5 — generated by TechainClone{pad}|\n"
        "//+------------------------------------------------------------------+\n"
        "#property strict\n"
        "#include <Trade/Trade.mqh>\n"
        "\n"
        "CTrade trade;\n"
        "\n"
        "int OnInit()\n"
        "{\n"
        "   return(INIT_SUCCEEDED);\n"
        "}\n"
        "\n"
        "void OnDeinit(const int reason)\n"
        "{\n"
        "}\n"
        "\n"
        "void OnTick()\n"
        "{\n"
        f"{body}\n"
        "}\n"
    )


# --------------------------------------------------------------------------
# Task 0.1 — SMA operand graph (sma_<id>[0])
# --------------------------------------------------------------------------
def test_golden_sma_operand_graph() -> None:
    graph = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "2", "type": "SMA", "data": {"period": 50}},
            {"id": "3", "type": "Condition",
             "data": {"left": "sma_2[0]", "operator": ">", "right": "1.2345"}},
            {"id": "4", "type": "Buy", "data": {"lots": 0.1}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
            {"source": "3", "target": "4"},
            {"source": "4", "target": "5"},
        ],
    }
    body = (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [SMA] node id=2\n"
        "   double sma_2[];\n"
        "   int h_sma_2 = iMA(_Symbol, _Period, 50, 0, MODE_SMA, PRICE_CLOSE);\n"
        "   CopyBuffer(h_sma_2, 0, 0, 1, sma_2);\n"
        "   // [Condition] node id=3\n"
        "   if (!(sma_2[0] > 1.2345)) return;\n"
        "   // [Buy] node id=4\n"
        '   trade.Buy(0.1, _Symbol, 0.0, 0, 0, "buy");\n'
        "   // [End] node id=5\n"
        "   // --- Strategy logic ends ---"
    )
    assert generate_mql5(graph, ea_name="GoldSmaEA") == _wrap("GoldSmaEA", body)


# --------------------------------------------------------------------------
# Task 0.2 — RSI and MACD operand graphs (single `value` operand [0])
# --------------------------------------------------------------------------
def test_golden_rsi_operand_graph() -> None:
    graph = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "2", "type": "RSI", "data": {"period": 21}},
            {"id": "3", "type": "Condition",
             "data": {"left": "rsi_2[0]", "operator": "<", "right": "30"}},
            {"id": "4", "type": "Buy", "data": {"lots": 0.5}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
            {"source": "3", "target": "4"},
            {"source": "4", "target": "5"},
        ],
    }
    body = (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [RSI] node id=2\n"
        "   double rsi_2[];\n"
        "   int h_rsi_2 = iRSI(_Symbol, _Period, 21, PRICE_CLOSE);\n"
        "   CopyBuffer(h_rsi_2, 0, 0, 1, rsi_2);\n"
        "   // [Condition] node id=3\n"
        "   if (!(rsi_2[0] < 30)) return;\n"
        "   // [Buy] node id=4\n"
        '   trade.Buy(0.5, _Symbol, 0.0, 0, 0, "buy");\n'
        "   // [End] node id=5\n"
        "   // --- Strategy logic ends ---"
    )
    assert generate_mql5(graph, ea_name="GoldRsiEA") == _wrap("GoldRsiEA", body)


def test_golden_macd_operand_graph() -> None:
    graph = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "2", "type": "MACD",
             "data": {"fast_ema": 12, "slow_ema": 26, "signal": 9}},
            {"id": "3", "type": "Condition",
             "data": {"left": "macd_2[0]", "operator": ">", "right": "0"}},
            {"id": "4", "type": "Buy", "data": {"lots": 0.1}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
            {"source": "3", "target": "4"},
            {"source": "4", "target": "5"},
        ],
    }
    body = (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [MACD] node id=2\n"
        "   double macd_2[];\n"
        "   int h_macd_2 = iMACD(_Symbol, _Period, 12, 26, 9, PRICE_CLOSE);\n"
        "   CopyBuffer(h_macd_2, MAIN_LINE, 0, 1, macd_2);\n"
        "   // [Condition] node id=3\n"
        "   if (!(macd_2[0] > 0)) return;\n"
        "   // [Buy] node id=4\n"
        '   trade.Buy(0.1, _Symbol, 0.0, 0, 0, "buy");\n'
        "   // [End] node id=5\n"
        "   // --- Strategy logic ends ---"
    )
    assert generate_mql5(graph, ea_name="GoldMacdEA") == _wrap("GoldMacdEA", body)


# --------------------------------------------------------------------------
# rsi-enrichment Phase 0 — RSI Condition with LITERAL operands only.
# The operand-resolver translation MUST leave literals untouched (string-
# identical), so this graph's guard stays byte-identical after wiring up
# translate_operand. The plain ref RSI->Condition case is already covered by
# ``test_golden_rsi_operand_graph`` (operand ``rsi_2[0]``).
# --------------------------------------------------------------------------
def test_golden_rsi_literal_operand_condition() -> None:
    graph = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "2", "type": "RSI", "data": {"period": 14}},
            {"id": "3", "type": "Condition",
             "data": {"left": "70", "operator": ">", "right": "30"}},
            {"id": "4", "type": "Buy", "data": {"lots": 0.1}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
            {"source": "3", "target": "4"},
            {"source": "4", "target": "5"},
        ],
    }
    body = (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [RSI] node id=2\n"
        "   double rsi_2[];\n"
        "   int h_rsi_2 = iRSI(_Symbol, _Period, 14, PRICE_CLOSE);\n"
        "   CopyBuffer(h_rsi_2, 0, 0, 1, rsi_2);\n"
        "   // [Condition] node id=3\n"
        "   if (!(70 > 30)) return;\n"
        "   // [Buy] node id=4\n"
        '   trade.Buy(0.1, _Symbol, 0.0, 0, 0, "buy");\n'
        "   // [End] node id=5\n"
        "   // --- Strategy logic ends ---"
    )
    assert generate_mql5(graph, ea_name="GoldRsiLitEA") == _wrap(
        "GoldRsiLitEA", body
    )


# --------------------------------------------------------------------------
# Task 0.3 — Stochastic %K/%D graph (raw stochk_/stochd_ reads)
# --------------------------------------------------------------------------
def test_golden_stochastic_k_d_graph() -> None:
    graph = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "X", "type": "Stochastic", "data": {}},
            {"id": "3", "type": "Condition",
             "data": {"left": "stochk_X[0]", "operator": ">", "right": "stochd_X[0]"}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "X"},
            {"source": "X", "target": "3"},
            {"source": "3", "target": "5"},
        ],
    }
    body = (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [Stochastic] node id=X\n"
        "   double stochk_X[];\n"
        "   double stochd_X[];\n"
        "   int h_stoch_X = iStochastic(_Symbol, _Period, 14, 3, 3, MODE_SMA, STO_LOWHIGH);\n"
        "   CopyBuffer(h_stoch_X, MAIN_LINE, 0, 1, stochk_X);\n"
        "   CopyBuffer(h_stoch_X, SIGNAL_LINE, 0, 1, stochd_X);\n"
        "   // [Condition] node id=3\n"
        "   if (!(stochk_X[0] > stochd_X[0])) return;\n"
        "   // [End] node id=5\n"
        "   // --- Strategy logic ends ---"
    )
    assert generate_mql5(graph, ea_name="GoldStochEA") == _wrap(
        "GoldStochEA", body
    )


# --------------------------------------------------------------------------
# Task 0.4 — Crossing graphs ([s]/[s+1] + s+2 copy depth)
# --------------------------------------------------------------------------
def _cross_graph(cross_type: str, cross_data: dict) -> dict:
    """Start -> SMA(A) -> End with crossing X fed by value1=A, value2=B."""
    return {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "A", "type": "SMA", "data": {"period": 10}},
            {"id": "B", "type": "SMA", "data": {"period": 20}},
            {"id": "X", "type": cross_type, "data": cross_data},
            {"id": "9", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "A"},
            {"source": "A", "target": "9"},
            {"source": "X", "target": "9"},
            {"source": "A", "target": "X", "targetHandle": "value1"},
            {"source": "B", "target": "X", "targetHandle": "value2"},
        ],
    }


def _cross_body(label: str, depth: int, before_op: str, now_op: str, s: int) -> str:
    """Build the expected OnTick body for a crossing graph at depth/s."""
    return (
        "   // [Start] node id=1\n"
        "   // --- Strategy logic begins ---\n"
        "   // [SMA] node id=A\n"
        "   double sma_A[];\n"
        "   int h_sma_A = iMA(_Symbol, _Period, 10, 0, MODE_SMA, PRICE_CLOSE);\n"
        "   ArraySetAsSeries(sma_A, true);\n"
        f"   CopyBuffer(h_sma_A, 0, 0, {depth}, sma_A);\n"
        "   // [SMA] node id=B\n"
        "   double sma_B[];\n"
        "   int h_sma_B = iMA(_Symbol, _Period, 20, 0, MODE_SMA, PRICE_CLOSE);\n"
        "   ArraySetAsSeries(sma_B, true);\n"
        f"   CopyBuffer(h_sma_B, 0, 0, {depth}, sma_B);\n"
        f"   // [{label}] node id=X\n"
        f"   if (!(sma_A[{s + 1}] {before_op} sma_B[{s + 1}]"
        f" && sma_A[{s}] {now_op} sma_B[{s}])) return;\n"
        "   // [End] node id=9\n"
        "   // --- Strategy logic ends ---"
    )


def test_golden_bullish_cross_default_depth3() -> None:
    code = generate_mql5(_cross_graph("BullishCross", {}), ea_name="GoldBullEA")
    expected = _wrap(
        "GoldBullEA",
        _cross_body("BullishCross", depth=3, before_op="<", now_op=">", s=1),
    )
    assert code == expected


def test_golden_bearish_cross_default_depth3() -> None:
    code = generate_mql5(_cross_graph("BearishCross", {}), ea_name="GoldBearEA")
    expected = _wrap(
        "GoldBearEA",
        _cross_body("BearishCross", depth=3, before_op=">", now_op="<", s=1),
    )
    assert code == expected


def test_golden_bullish_cross_s2_depth4() -> None:
    code = generate_mql5(
        _cross_graph("BullishCross", {"barras_confirmacion": 2}),
        ea_name="GoldBullS2EA",
    )
    expected = _wrap(
        "GoldBullS2EA",
        _cross_body("BullishCross", depth=4, before_op="<", now_op=">", s=2),
    )
    assert code == expected


# --------------------------------------------------------------------------
# node-grouping guardrail — a top-level ``groups`` key is a render-only editor
# overlay and MUST be INVISIBLE to codegen. The generated MQL5 has to be
# BYTE-IDENTICAL whether or not the graph carries ``groups``. This locks the
# "codegen no-op" invariant for the node-grouping feature.
# --------------------------------------------------------------------------
def test_groups_key_is_byte_identical_codegen_noop() -> None:
    base = {
        "nodes": [
            {"id": "1", "type": "Start", "data": {}},
            {"id": "2", "type": "SMA", "data": {"period": 50}},
            {"id": "3", "type": "Condition",
             "data": {"left": "sma_2[0]", "operator": ">", "right": "1.2345"}},
            {"id": "4", "type": "Buy", "data": {"lots": 0.1}},
            {"id": "5", "type": "End", "data": {}},
        ],
        "edges": [
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
            {"source": "3", "target": "4"},
            {"source": "4", "target": "5"},
        ],
    }
    # Same graph, plus a render-only ``groups`` overlay referencing real members.
    with_groups = {
        **base,
        "groups": [{"id": "g1", "name": "Entry", "nodeIds": ["2", "3"]}],
    }

    without = generate_mql5(base, ea_name="GroupNoOpEA")
    withg = generate_mql5(with_groups, ea_name="GroupNoOpEA")
    assert withg == without
