/**
 * Thin typed fetch wrapper used by every dashboard component that talks to
 * the FastAPI backend.
 *
 * Design notes:
 * - All requests go to same-origin `/api/*`. The Next.js dev proxy
 *   (`next.config.ts` → `rewrites()`) forwards them to FastAPI. In prod the
 *   same path will be served by the reverse proxy in front of both apps.
 * - `credentials: "include"` is mandatory so the httpOnly access cookie is
 *   sent on every request.
 * - State-changing verbs (POST/PUT/PATCH/DELETE) automatically attach the
 *   CSRF header via `withCsrfHeader()`.
 *
 * Typed-paths note (Phase 5):
 * - We now import `paths` / `components` from `@aether/shared-types`, which
 *   is generated by `openapi-typescript` from `apps/api/openapi.json`.
 * - The committed schema is currently a **placeholder** (empty paths /
 *   components). Until the backend runs `make gen.types` and commits the
 *   real OpenAPI dump, `ApiResponse<P, M>` will resolve to `never` for any
 *   `(P, M)` pair. The `apiGet`/`apiPost`/... helpers below keep their
 *   generic `<T>` signature so call sites stay compilable in the meantime;
 *   typed helpers should be adopted incrementally once the real schema
 *   lands.
 */

import type { paths, components } from "@aether/shared-types";

import { withCsrfHeader } from "@/lib/auth";

export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;
  constructor(message: string, status: number, body: unknown) {
    super(message);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }
}

const STATE_CHANGING_METHODS = new Set(["POST", "PUT", "PATCH", "DELETE"]);

// Endpoints that must NEVER trigger the auto-refresh retry below, otherwise
// we'd recurse / mask the user's intent (e.g. retrying /logout after it 401s
// would re-authenticate the session you just tore down).
const REFRESH_EXEMPT_PATHS = new Set([
  "/api/auth/login",
  "/api/auth/refresh",
  "/api/auth/logout",
]);

// Single-flight refresh promise. Multiple concurrent 401s (page loads several
// resources at once) all await the same refresh call instead of each firing
// their own — without this, N parallel calls cause N refresh attempts and the
// backend rotates the refresh token N times, racing each other into 401s.
let inFlightRefresh: Promise<boolean> | null = null;

async function attemptRefresh(): Promise<boolean> {
  if (inFlightRefresh) return inFlightRefresh;
  inFlightRefresh = (async () => {
    try {
      const res = await fetch("/api/auth/refresh", {
        method: "POST",
        credentials: "include",
        headers: withCsrfHeader().headers,
      });
      return res.ok;
    } catch {
      return false;
    } finally {
      // Tiny defer so any 401s that lost the race read the new cookies before
      // we null this out. Important on Safari which sometimes lags Set-Cookie.
      setTimeout(() => {
        inFlightRefresh = null;
      }, 0);
    }
  })();
  return inFlightRefresh;
}

function redirectToLogin(): void {
  if (typeof window === "undefined") return;
  const here = window.location.pathname + window.location.search;
  // Avoid loop if we're already on /login.
  if (window.location.pathname.startsWith("/login")) return;
  const url = new URL("/login", window.location.origin);
  url.searchParams.set("return_to", here);
  window.location.href = url.toString();
}

async function buildFinalInit(
  init: RequestInit & { method?: string },
): Promise<{ method: string; finalInit: RequestInit }> {
  const method = (init.method ?? "GET").toUpperCase();
  const headers = new Headers(init.headers ?? {});
  if (!headers.has("Accept")) headers.set("Accept", "application/json");
  if (init.body && !headers.has("Content-Type")) {
    headers.set("Content-Type", "application/json");
  }
  let finalInit: RequestInit = {
    ...init,
    method,
    headers,
    credentials: "include",
  };
  if (STATE_CHANGING_METHODS.has(method)) {
    finalInit = withCsrfHeader(finalInit);
  }
  return { method, finalInit };
}

async function request<T>(
  path: string,
  init: RequestInit & { method?: string } = {},
): Promise<T> {
  const { finalInit } = await buildFinalInit(init);

  let res = await fetch(path, finalInit);

  // Auto-refresh on 401 (expired access cookie) or 403 (CSRF cookie also
  // expired — same TTL as access). One retry, single-flight, then redirect.
  // /api/auth/* endpoints are exempt to avoid recursion.
  if ((res.status === 401 || res.status === 403) && !REFRESH_EXEMPT_PATHS.has(path)) {
    const refreshed = await attemptRefresh();
    if (refreshed) {
      // Rebuild init so the CSRF header picks up the rotated cookie value.
      const { finalInit: retryInit } = await buildFinalInit(init);
      res = await fetch(path, retryInit);
    } else {
      // Refresh failed — session is truly dead. Bounce to login with return_to.
      redirectToLogin();
      throw new ApiError(`Session expired`, res.status, { detail: "session expired" });
    }
  }

  // 204 No Content / empty body — return undefined cast to T.
  if (res.status === 204) return undefined as T;

  const contentType = res.headers.get("Content-Type") ?? "";
  const body: unknown = contentType.includes("application/json")
    ? await res.json()
    : await res.text();

  if (!res.ok) {
    throw new ApiError(
      `Request to ${path} failed with ${res.status}`,
      res.status,
      body,
    );
  }
  return body as T;
}

export function apiGet<T>(path: string, init?: RequestInit): Promise<T> {
  return request<T>(path, { ...init, method: "GET" });
}

export function apiPost<T>(
  path: string,
  body?: unknown,
  init?: RequestInit,
): Promise<T> {
  return request<T>(path, {
    ...init,
    method: "POST",
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

export function apiPut<T>(
  path: string,
  body?: unknown,
  init?: RequestInit,
): Promise<T> {
  return request<T>(path, {
    ...init,
    method: "PUT",
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

export function apiPatch<T>(
  path: string,
  body?: unknown,
  init?: RequestInit,
): Promise<T> {
  return request<T>(path, {
    ...init,
    method: "PATCH",
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

export function apiDelete<T>(path: string, init?: RequestInit): Promise<T> {
  return request<T>(path, { ...init, method: "DELETE" });
}

// ---------------------------------------------------------------------------
// Typed helpers backed by @aether/shared-types
// ---------------------------------------------------------------------------
//
// `ApiResponse<P, M>` extracts the 200/application-json response body type
// from the generated OpenAPI `paths` map.
//
// Usage:
//   type Projects = ApiResponse<"/api/projects", "get">;
//   const data = await apiGet<Projects>("/api/projects");
//
// Until the real OpenAPI schema is regenerated (see
// `packages/shared-types/README.md` and the `make gen.types` target),
// `paths` is `Record<string, never>`, so this type resolves to `never` for
// every concrete `(P, M)` pair. That is intentional: it forces
// regeneration before typed call sites can be added in earnest.
export type ApiResponse<
  P extends keyof paths,
  M extends keyof paths[P],
> = paths[P][M] extends {
  responses: { 200: { content: { "application/json": infer T } } };
}
  ? T
  : never;

// Re-export the generated `components` type so call sites can reach for
// `Schemas["User"]` etc. without importing from @aether/shared-types
// directly. Same caveat applies: until the real schema lands, the
// `components.schemas` map is empty.
export type Schemas = components["schemas"];
