"""The standalone Python script template (pure stdlib).

The generated program is broker-agnostic: it takes a CHRONOLOGICAL list of OHLC
``Bar`` records (oldest -> newest), precomputes every indicator series once in
``compute_indicators(bars)``, then walks the bars calling ``on_bar(i, bars, ind)``
which evaluates the strategy logic and emits signals. The ``__main__`` block reads
a CSV via the stdlib ``csv`` module so the script runs end-to-end with no install.

Bar-index convention (the single rule honored by every node generator):
an MQL5 series read ``var[s]`` (s bars back from the current bar) maps to
``_at(ind["var"], i, s)`` == ``ind["var"][i - s]``. Out-of-range / warmup reads
return ``None`` and the guards treat a ``None`` operand as a non-firing branch.
"""

from __future__ import annotations

# Header / imports / Bar type / per-bar read helper. ``__EA_NAME__`` is replaced
# by the generator. Pure stdlib only: math, csv, sys, typing.NamedTuple.
HEADER = '''"""__EA_NAME__ — generated by TechainClone.

Standalone, broker-agnostic trading logic in PURE Python (stdlib only).
Feed it a chronological list of OHLC bars; it returns the signals per bar.
"""

from __future__ import annotations

import csv
import math
import sys
from typing import NamedTuple


class Bar(NamedTuple):
    """A single OHLC bar. ``time`` is an opaque label (often an ISO string)."""

    time: str
    open: float
    high: float
    low: float
    close: float


def _at(series, i, shift=0):
    """Return ``series[i - shift]`` or None when out of range / warmup.

    This is the bar-index bridge: MQL5 ``var[shift]`` (shift bars back from the
    current bar) maps to ``series[i - shift]`` on the chronological list.
    """
    j = i - shift
    if series is None or j < 0 or j >= len(series):
        return None
    return series[j]


_CMP = {
    ">": lambda a, b: a > b,
    "<": lambda a, b: a < b,
    ">=": lambda a, b: a >= b,
    "<=": lambda a, b: a <= b,
    "==": lambda a, b: a == b,
    "!=": lambda a, b: a != b,
}


def _cmp(left, op, right):
    """None-safe comparison: a None operand (warmup) yields False, never raises."""
    if left is None or right is None:
        return False
    fn = _CMP.get(op)
    return False if fn is None else fn(left, right)'''


# compute_indicators: precompute every indicator series once over the full
# history. ``__COMPUTE_BODY__`` holds the per-indicator-node assignments; an empty
# body still returns a valid (empty) dict.
COMPUTE = '''def compute_indicators(bars):
    """Precompute all indicator series; returns a {name: list} dict aligned to bars."""
    ind = {}
__COMPUTE_BODY__
    return ind'''


# on_bar: evaluate the strategy for bar ``i``. Returns a list of signal dicts.
# Guards ``return signals`` early to abort the bar, mirroring MQL5 ``return;``.
ON_BAR = '''def on_bar(i, bars, ind):
    """Evaluate the strategy at bar ``i``; return a list of emitted signals."""
    signals = []
__ON_BAR_BODY__
    return signals'''


# run + __main__: walk the bars and drive on_bar; the demo loads a CSV.
RUNNER = '''def run(bars):
    """Run the strategy over a chronological list of ``Bar`` and collect signals."""
    ind = compute_indicators(bars)
    out = []
    for i in range(len(bars)):
        for sig in on_bar(i, bars, ind):
            out.append({"bar": i, **sig})
    return out


def load_csv(path):
    """Load OHLC bars from a CSV with a time/open/high/low/close header."""
    bars = []
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            bars.append(
                Bar(
                    time=row.get("time", ""),
                    open=float(row["open"]),
                    high=float(row["high"]),
                    low=float(row["low"]),
                    close=float(row["close"]),
                )
            )
    return bars


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python __EA_NAME__.py <bars.csv>")
        raise SystemExit(2)
    for signal in run(load_csv(sys.argv[1])):
        print(signal)'''


def render_script(
    ea_name: str, compute_body: str, on_bar_body: str, indicator_lib: str
) -> str:
    """Assemble the full standalone script from its sections.

    ``compute_body`` / ``on_bar_body`` are already-indented snippet blocks; an
    empty block is replaced with a ``pass`` line so the function body is valid.
    ``indicator_lib`` is the pure-stdlib indicator helper block. Sentinel
    placeholders (not ``str.format``) are used so the literal ``{`` / ``}`` braces
    in the templates need no escaping.
    """
    compute = compute_body or "    pass"
    on_bar = on_bar_body or "    pass"
    header = HEADER.replace("__EA_NAME__", ea_name)
    runner = RUNNER.replace("__EA_NAME__", ea_name)
    return (
        header
        + "\n\n\n"
        + indicator_lib
        + "\n\n\n"
        + COMPUTE.replace("__COMPUTE_BODY__", compute)
        + "\n\n\n"
        + ON_BAR.replace("__ON_BAR_BODY__", on_bar)
        + "\n\n\n"
        + runner
        + "\n"
    )
